### ISSUE TITLE
long code line breaks width (html pre tag)

### ISSUE THREAD

**Issue by mauk81** [grails/grails-doc#167]
i get a unnecessary horizontal scroll bar as a result of a long code line in [3 Upgrading from Grails 2.2](http://grails.org/doc/2.3.x/guide/upgradingFromPreviousVersionsOfGrails.html)

**Comment by Dhanendra-jft** [comment]
@graemerocher @jeffbrown @guramritpal-jft, I worked on this issue and found the root cause. As per the title of issue this error is due to the pre tag, I suspected that in a pre tag we have a child p tag with a class - paragraph, we have to add another class which has css property:-

width: {:HINT};
word-wrap: break-word;//or can be skipped if we want a scroll bar

HINT: can be added dynamically according to width of users screen in px or by using media tag i don't know the actual way of doing this.

**Comment by jameskleeh** [comment]
Closing because of 2.x
