### ISSUE TITLE
More info for plugin descriptor needed

### ISSUE THREAD

**Issue by anshbansal** [grails/grails-doc#317]
I was looking at https://github.com/grails3-plugins/geb/blob/master/src/main/groovy/geb/GebGrailsPlugin.groovy when I noticed that the plugin descriptor has license, issueManagement, scm which are not documented in the documentation. 

Are these part of "special properties"? Also what is so special with these special properties. This is not documented.

**Comment by graemerocher** [comment]
They are documentation properties used to display information when the `grails plugin-info` command is run

**Comment by anshbansal** [comment]
I checked https://github.com/grails/grails-profile-repository/blob/master/profiles/base/commands/plugin-info.groovy and saw that it was getting the details from https://repo.grails.org/grails/plugins3/org/grails/plugins. How do the details go there? Are they synced via Bintray?

**Comment by anshbansal** [comment]
Plugin info does not show all information currently said in the documentation. That's why asking this.

**Comment by graemerocher** [comment]
No because some of it just goes into plugin descriptor which historically has been parsed by the website (see https://repo.grails.org/grails/plugins3/org/grails/plugins/feeds/2.0.0-SNAPSHOT/feeds-2.0.0-20150626.092110-1-plugin.xml) for an example descriptor.

This information could be used by any tool or website to get more information about the plugin.

**Comment by guramritpal-jft** [comment]
@anshbansal  do you think your issue has been solved or still you have doubt on this issue.
